# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0K_FVd6rJzAaqlX-omTKDiU34gUbKj0

# corte 1
"""

print("Hola mundo")

nombre=input("¿Cual es tu nombre?")

print("hola mundo de", nombre)

nombre="nathalia"
edad=17
altura=1.55
correo="nathalia.7diez@gamil.com"
soltero=True
print("tipos de datos:")
print(type(nombre))
print(type(soltero))
print(type(altura))
print(type(correo))
print(type(edad))

print("Hola",nombre, "tienes", edad -10)

