# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5tsvfEYsMzVsA0yujaVvlSYrZ9gvOg_
"""

pedido="Laura Gómez", 3, 45500.0, False, "Calle 45 #12-30"
print"cliente",pedido[0]
print"direccion"pedido[-1]