# -*- coding: utf-8 -*-
"""tema 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d1n1RV9omU9ShHAYSWG-WIwFd_ai4qas
"""

df_tema1 = df[['Tema 1']]
display(df_tema1.head())

"""### Parámetros de distribución para 'Tema 1'"""

print("Parámetros para la Distribución Normal (Tema 1):")
print(f"  Media = {normal_params['Tema 1']['mean']:.4f}")
print(f"  Desviación Estándar = {normal_params['Tema 1']['std']:.4f}")

print("\nParámetros para la Distribución Exponencial (Tema 1):")
print(f"  Lambda (Tasa) = {exponential_params['Tema 1']['lambda']:.4f}")

print("\nParámetros para la Distribución Uniforme (Tema 1):")
print(f"  Mínimo = {uniform_params['Tema 1']['min']:.4f}")
print(f"  Máximo = {uniform_params['Tema 1']['max']:.4f}")

"""Prueba de chi-cuadrada **para Tema 1**."""

from scipy.stats import chisquare, norm, expon, uniform
import numpy as np

def run_chi_squared_test(data, num_bins=5):
    # Remove NaN values from data
    data = data.dropna()

    # Only proceed if there's enough data
    if len(data) == 0:
        return {'Normal': {'chi2': np.nan, 'p_value': np.nan},
                'Exponential': {'chi2': np.nan, 'p_value': np.nan},
                'Uniform': {'chi2': np.nan, 'p_value': np.nan}}

    # Generate histogram data for observed frequencies
    hist, bin_edges = np.histogram(data, bins=num_bins)
    observed_frequencies = hist

    results = {}

    # --- Normal Distribution Test ---
    mean, std = norm.fit(data)
    cdf_normal = norm.cdf(bin_edges, loc=mean, scale=std)
    expected_probabilities_normal = np.diff(cdf_normal)
    expected_frequencies_normal = expected_probabilities_normal * len(data)

    # Normalize expected frequencies to sum to observed total
    total_observed = np.sum(observed_frequencies)
    total_expected_normal = np.sum(expected_frequencies_normal)
    if total_expected_normal > 0:
        expected_frequencies_normal = (expected_frequencies_normal / total_expected_normal) * total_observed
    else:
        # Handle case where all expected frequencies are zero
        expected_frequencies_normal = np.ones_like(observed_frequencies) * (total_observed / len(observed_frequencies))

    # Ensure no expected frequency is zero for chi-squared test
    expected_frequencies_normal[expected_frequencies_normal == 0] = 1e-9 # Small non-zero value

    chi2_normal, p_normal = chisquare(f_obs=observed_frequencies, f_exp=expected_frequencies_normal)
    results['Normal'] = {'chi2': chi2_normal, 'p_value': p_normal}

    # --- Exponential Distribution Test ---
    # If data contains non-positive values, exponential fit might fail or be inappropriate
    if (data <= 0).any():
        lambda_exp = np.nan
        p_exponential = np.nan
        chi2_exponential = np.nan
    else:
        lambda_exp = 1 / np.mean(data)
        cdf_exponential = expon.cdf(bin_edges, scale=1/lambda_exp)
        expected_probabilities_exponential = np.diff(cdf_exponential)
        expected_frequencies_exponential = expected_probabilities_exponential * len(data)

        # Normalize expected frequencies
        total_expected_exponential = np.sum(expected_frequencies_exponential)
        if total_expected_exponential > 0:
            expected_frequencies_exponential = (expected_frequencies_exponential / total_expected_exponential) * total_observed
        else:
            expected_frequencies_exponential = np.ones_like(observed_frequencies) * (total_observed / len(observed_frequencies))

        expected_frequencies_exponential[expected_frequencies_exponential == 0] = 1e-9

        chi2_exponential, p_exponential = chisquare(f_obs=observed_frequencies, f_exp=expected_frequencies_exponential)

    results['Exponential'] = {'chi2': chi2_exponential, 'p_value': p_exponential}

    # --- Uniform Distribution Test ---
    min_val, max_val = np.min(data), np.max(data)
    cdf_uniform = uniform.cdf(bin_edges, loc=min_val, scale=max_val - min_val)
    expected_probabilities_uniform = np.diff(cdf_uniform)
    expected_frequencies_uniform = expected_probabilities_uniform * len(data)

    # Normalize expected frequencies
    total_expected_uniform = np.sum(expected_frequencies_uniform)
    if total_expected_uniform > 0:
        expected_frequencies_uniform = (expected_frequencies_uniform / total_expected_uniform) * total_observed
    else:
        expected_frequencies_uniform = np.ones_like(observed_frequencies) * (total_observed / len(observed_frequencies))

    expected_frequencies_uniform[expected_frequencies_uniform == 0] = 1e-9

    chi2_uniform, p_uniform = chisquare(f_obs=observed_frequencies, f_exp=expected_frequencies_uniform)
    results['Uniform'] = {'chi2': chi2_uniform, 'p_value': p_uniform}

    return results

# Apply the chi-squared test only for 'Tema 1'
results_tema1 = run_chi_squared_test(df['Tema 1'])

print("Resultados de la prueba de chi-cuadrada para 'Tema 1':")
highest_p_value = -1
best_fit_dist = ''
for dist_name, res in results_tema1.items():
    if not np.isnan(res['p_value']):
        print(f"  {dist_name}: Chi2 = {res['chi2']:.4f}, p-valor = {res['p_value']:.4f}")
        if res['p_value'] > highest_p_value:
            highest_p_value = res['p_value']
            best_fit_dist = dist_name
    else:
        print(f"  {dist_name}: No aplicable (datos inválidos o insuficientes).")

if best_fit_dist:
    print(f"  La distribución que mejor se ajusta a 'Tema 1' es: {best_fit_dist} (p-valor = {highest_p_value:.4f})")
else:
    print("  No se pudo determinar la distribución que mejor se ajusta a 'Tema 1'.")

"""Según los resultados obtenidos:

La distribución Normal presenta un p-valor de 0.9834.
La distribución Exponencial y Uniforme muestran p-valores muy cercanos a cero (0.0000).
Dado que un p-valor más alto sugiere un mejor ajuste a la distribución hipotética, podemos concluir que la distribución Normal es la que mejor se ajusta a los datos de 'Tema 1'.

## Reporte de Resultados: Pruebas de Ajuste de Distribución para 'Tema 1'

El objetivo de este análisis fue determinar cuál de las distribuciones (Normal, Exponencial o Uniforme) mejor se ajusta a los datos de la variable 'Tema 1' utilizando la prueba de chi-cuadrada.

### Parámetros Estimados:

*   **Distribución Normal:**
    *   Media = 49.8284
    *   Desviación Estándar = 9.3213
*   **Distribución Exponencial:**
    *   Lambda (Tasa) = 0.0201
*   **Distribución Uniforme:**
    *   Mínimo = 20.6523
    *   Máximo = 80.4546

### Resultados de la Prueba de Chi-cuadrada:

Se aplicó la prueba de chi-cuadrada para comparar las frecuencias observadas en los datos de 'Tema 1' con las frecuencias esperadas bajo cada una de las distribuciones hipotéticas. Los p-valores obtenidos fueron los siguientes:

*   **Normal:** p-valor = 0.9834
*   **Exponencial:** p-valor = 0.0000
*   **Uniforme:** p-valor = 0.0000

### Conclusión:

Un p-valor alto (generalmente mayor que 0.05) indica que no hay evidencia suficiente para rechazar la hipótesis nula, es decir, que los datos se ajustan bien a la distribución hipotética. Por el contrario, un p-valor bajo (menor que 0.05) sugiere que los datos no se ajustan a la distribución.

Basado en los resultados:

*   La **distribución Normal** presenta un p-valor de 0.9834, que es significativamente alto. Esto indica un excelente ajuste de los datos de 'Tema 1' a una distribución normal.
*   Las distribuciones **Exponencial y Uniforme** muestran p-valores muy cercanos a cero (0.0000), lo que sugiere que estas distribuciones no son adecuadas para modelar los datos de 'Tema 1'.

En consecuencia, podemos concluir con alta confianza que la **distribución Normal es la que mejor se ajusta a los datos de 'Tema 1'**.
"""