# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112zncRRNVZQEbTdsbSeG1T_4q94QrrER

corte 1
"""

print("hola mundo")

nombre=input("¿cual es tu nombre?")
print("hola mundo de ", nombre)

nombre="camilo"
edad=25
altura=1.75
correo="cmejiag@unab.edu.co"
casado=True

print("tipos de dato:")
print(type(nombre))
print (type(casado))
print(type(altura))
print(type(correo))
print(type(edad))

print("Hola",nombre,"tienes",edad-10)

cantidad =int(input("ingrese la cantidad de productos: "))
precio =float(input("ingrese el precio de cada producto:"))

subtotal = cantidad * precio

descuento = subtotal * 0.10

iva = subtotal * 0.19

total_antes_iva = subtotal - descuento

total_final = total_antes_iva + iva

print("subtotal:",subtotal)
print("descuento del 10%:",descuento)
print("iva del 19%",iva)
print("total a pagar antes del iva:",total_antes_iva)
print("valor final a pagar",total_final)

distancia = 100 #kms
rendmiento_spark = 22 #km/l
precio_litro = 4094 # ref 31 agosto

litros_necesarios = distancia / rendmiento_spark
print(f"Cantidad de litros necesarios para este viaje es de {litros_necesarios}")

costo_gasolina = precio_litro * litros_necesarios
print(f"\r El costo de la gasolina para este vaije es de {costo_gasolina}")

inflacion_petro = precio_litro * 1.08
print(f"\rEl costo del combustible cuando sube un 8% es de {inflacion_petro}")

costo_entre_3 = costo_gasolina / 3
print(f"\rpagando entre 3 sale a {costo_entre_3}")

ida_vuelta = costo_gasolina * 2
print(f"\rpagando entre 3 sale a {ida_vuelta}")

