# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zX3DJsenHjJLbcCTs7xzArkojIoouQt3
"""

cuantosNumerossumar= int(input("¿cuantos numeros deseas sumar?"))

acomuladossuma=0

for i in range(cuantosNumerossumar):
  numero= int(input("dame el numero que quiere sumar"))
  acomuladosuma = acomuladosuma + numero

  print("la suma es"), acomuladosuma
  ¿cuantos numeros deseas sumar? 5
  Dame el numero que quieres sumar4
  Dame el numero que quieres sumar3
  Dame el numero que quieres sumar4
  Dame el numero que quieres sumar4
  Dame el numero que quieres sumar4
  la suma es 19