# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HNXao6b0BnpByDR6Bm0y6isOX5EDZQ-H
"""

edad=int(input("ingrese su edad"))

if edad < 0:
  print("edad no valida")

elif edad <= 12:
 print("niño")

elif edad >= 13 and edad <=17:
  print("adolescente")

elif edad >= 18 and edad <=59:
   print("adulto")
else:
  print("adulto mayor")

nota=float(input("ingrese su nota final(0.0 a 5.0):"))
if nota< 0.0 or nota >5.0:
  print("valor fuera de rango")
elif nota >=3.0:
  print("aprobo")
elif nota >= 2.5 and nota <= 2.99:
  print("habiltacion")
else:
  print("reprobo")

rol=input("ingrese su rol (estudiante/docente/administrador:)")
if rol=="estudiante":
  print("bienvenido/a estudiante")
elif rol=="estudiante":
  print("bienvenido/a docente")
elif rol=="estudiante":
  print("bienvenido/a administrador")
else:
  print("no valido")

peso = float(input("ingrese su peso en kg:"))
estatura = float(input("ingrese su estatura en metros"))
imc=peso / (estatura**2)

if imc < 18.5:
  print("bajo peso")
elif imc <= 18.5 and imc >=24.9:
  print("peso normal")
elif imc <= 25.0 and imc >= 29.9:
  print("sobrepeso")
elif imc >= 30.0:
  print("obesidad")
else:
  print("no valido")

compra= float(input("ingrese el valor de la compra:"))
respuesta = input("¿Es estudiante?(si/no):")
es_estudiante = respuesta =="si"

descuento=0.0
if es_estudiante :
  descuento+=0.15
elif compra >= 200000:
  descuento +=0.05

descuento_real=descuento * compra
print(f"el total de la compra es {compra-descuento_real}")



