# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BM2M0pCNvS_93uGPxGST0isrRnCnSZEg
"""

pedido = ["Laura Gómez", 3, 45500.0, False, "Calle 45 #12-30"]
print("Cliente:", pedido[0])
print("Dirección:", pedido[-1])

pedido[1] = 5
pedido[2] = 62300.0
pedido[3] = True
print("Pedido corregido:", pedido)

pedido.insert(1, "3001234567")
pedido.append("Andrés")
print("Con teléfono y domiciliario:", pedido)

pedido.append(10)
pedido.append(30)
print("Lista completa:", pedido)
print("Cantidad de elementos:", len(pedido))

print("(a) Nombre y teléfono:", pedido[0:2])
print("(b) Productos, total y pago:", pedido[2:5])
print("(c) Tres últimos datos:", pedido[-3:])
print("(d) Lista invertida:", pedido[::-1])

