# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDjTWIXQBKlyKzacdTgMWnVZIN2URJWW
"""

edad = int(input("Edad: "))
esPreventa = input("¿Es preventa? (Si/No): ")
cantidadEntradas = int(input("Cantidad de entradas: "))
if cantidadEntradas >= 10:
    precio = 50000
elif edad < 12 or edad > 70:
    precio = 40000
elif esPreventa == "Si" and cantidadEntradas >= 4:
    precio = 45000
elif esPreventa == "Si":
    precio = 60000
else:
    precio = 80000

total = precio * cantidadEntradas
print("Precio por entrada: $"
, precio)
print("Total de la compra: $", total)